version: '3'

services:
  db:
    container_name: brundij-db-postgres
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brundij 
        #  app:
        #    container_name: brundij-app-dev
        #    build:
        #      context: .
        #      dockerfile: Dockerfile.dev
        #    ports:
        #      - 4000:4000
        #    environment:
        #     PORT: 4000
        #     DATABASE_HOST: db 
        #     DATABASE_USER: postgres
        #     DATABASE_PASSWORD: postgres
        #     DATABASE_NAME: brundij 
        #     DATABASE_PORT: 5432
