version: '3'

services:
  db:
    container_name: brundij-db-postgres
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brundij 
  test_db:
    container_name: brundij-db-postgres-test
    image: postgres:13-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: brundij
